[install]
cmake = {}
gcc = {}
ncurses = {}
coreutils = {} # to get around realpath bug for now

[hook]
script = """
	alias build="cmake -DCURSES_LIBRARY=$FLOX_ENV/lib/libncurses.so -DCURSES_INCLUDE_PATH=$FLOX_ENV/include . && make -j5"
	alias run="./nrogue"
"""

