name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_VERSION_TEXT: build-${{ github.run_number }}
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: PRINT ENV
      run: |
           echo $PATH
           echo $ENV
           echo $PATH
           ls C:/
           ls C:/msys64/
           ls C:/msys64/mingw64
           ls C:/msys64/mingw64/bin
           
    
